const int EVENT_TYPES_HAS_ECHO_FIELD_ID = 2001;
const int EVENT_EMITTERS_TYPE_ID_FIELD_ID = 2001;
const int EVENT_EMITTERS_IS_ONLINE_FIELD_ID = 2002;
const int EVENT_LISTENERS_TYPE_ID_FIELD_ID = 2001;
const int EVENT_LISTENERS_LISTENABLE_TYPES_FIELD_ID = 2002;
